config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :projects, shallow: true do
    resources :retros do
      resources :issues do
        resources :outstandings
        resources :votes
      end
    end
  end

  resources :users

  root   'projects#index'

  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'admin_access_required' => 'page#admin_access_required'
  get    'owner_access_required' => 'page#owner_access_required'

  # custom route for moving the retro from one step to the next
  post   'retros/:id/status/:status' => 'retros#transition_status', as: :transition_retro_status
  post 'issues/:issue_id/votes' => 'votes#create', as: :make_new_vote

  get 'users/:retro_id/votes', :to => 'votes#clear_all', as: :clear_user_votes
  post 'retros/:id/discussed', :to => 'retros#increment_discussed_review', as: :increment_discussed_review
  post 'retros/:id/discussed_followup', :to => 'retros#increment_discussed_followup', as: :increment_discussed_followup
  post 'retros/:retro_id/outstandings/:id/complete', :to => 'outstandings#mark_complete', as: :mark_complete

end

app/models/outstanding.rb
class Outstanding < ActiveRecord::Base
  belongs_to :issue
  has_and_belongs_to_many :users
  validates :description, presence: true, length:{minimum:2}
  validates :retro_id, presence: true
  validates :issue_id, presence: true

end

app/controllers/outstandings_controller.rb
require 'pusher'

Pusher.app_id = '133467'
Pusher.key = 'bec060895b93f6745a24'
Pusher.secret = 'd3e13b0e84b33a44613a'


class OutstandingsController < ApplicationController
  before_action :logged_in
  skip_before_action :authenticate!, only: [ :index, :show ]
  before_action :set_outstanding, only: [:show, :mark_complete, :edit, :update, :destroy]
  before_action :owner, only: [:mark_complete, :edit, :update, :destroy]
  respond_to :js

  def new
    @outstanding = Outstanding.new
    @outstanding.issue_id = params[:issue_id]
    @issue = Issue.find(@outstanding.issue_id)
    @outstanding.retro_id = @issue.retro_id
    @retro = Retro.find(@outstanding.retro_id)
    @outstanding.creator_id = current_user.id
    @outstanding.complete = false
  end

  def index
    @tasks = Outstanding.where("issue_id = #{params[:issue_id]}")
    @issue = Issue.find(params[:issue_id])
    @retro = Retro.find(@issue.retro_id)
  end

  def show
  end

  def create
    @outstanding = Outstanding.new(outstanding_params)
    @outstanding.issue_id = params[:issue_id]
    @issue = Issue.find(@outstanding.issue_id)
    @outstanding.retro_id = @issue.retro_id
    @retro = Retro.find(@outstanding.retro_id)
    @outstanding.creator_id = current_user.id
    @outstanding.complete = false
    if params[:assigned_to].nil?
      @assigned_users = nil
    elsif params[:assigned_to].include? ("-1")
      @assigned_users = User.all
    else
      @assigned_users = User.find(params[:assigned_to])
    end
    respond_to do |format|
      if @assigned_users != nil && @outstanding.save
        @outstanding.users << @assigned_users
        @index = Issue.where("retro_id = #{@retro.id} AND issue_type = '#{@issue.issue_type}'").order('votes_count DESC').index @issue
        flash[:success] = "Outstanding #{@outstanding.id} was successfully created"
        format.html { redirect_to @retro }
        if params[:assigned_to].include? ("-1")
          format.json { render json: {task: @outstanding,
                                      issue: @issue,
                                      users: 1 }}
          Pusher.trigger('retro_channel', 'create-task-event', {task: @outstanding,
                                                             issue: @issue,
                                                             users: 1 })
        else
          format.json { render json: {task: @outstanding,
                                      issue: @issue,
                                      users: @outstanding.users,
                                      user_size: @outstanding.users.size }}
          Pusher.trigger('retro_channel', 'create-task-event', {task: @outstanding,
                                                             issue: @issue,
                                                             users: @outstanding.users,
                                                             user_size: @outstanding.users.size })
        end
      else
        format.html { redirect_to @retro }
        format.json { render json: @outstanding.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if params[:assigned_to].nil?
      @assigned_users = nil
    elsif params[:assigned_to].include? ("-1")
      @assigned_users = User.all
    else
      @assigned_users = User.find(params[:assigned_to])
    end
    respond_to do |format|
      if @outstanding.update(outstanding_params)
        if @assigned_users != nil
          @outstanding.users.clear
          @outstanding.users << @assigned_users
        end
        format.html { redirect_to @retro }
        if params[:assigned_to].include? ("-1")
          format.json { render json: {task: @outstanding,
                                      issue: @issue,
                                      users: 1 }}
          Pusher.trigger('retro_channel', 'update-task-event', {task: @outstanding,
                                                                issue: @issue,
                                                                users: 1 })
        else
          format.json { render json: {task: @outstanding,
                                      issue: @issue,
                                      users: @outstanding.users,
                                      user_size: @outstanding.users.size }}
          Pusher.trigger('retro_channel', 'update-task-event', {task: @outstanding,
                                                                issue: @issue,
                                                                users: @outstanding.users,
                                                                user_size: @outstanding.users.size })
        end
      else
        format.html { render :edit }
        format.json { render json: @outstanding.errors, status: :unprocessable_entity }
      end
    end
  end

  def mark_complete
    if @outstanding.complete?
      @outstanding.complete = false
    else
      @outstanding.complete = true
    end
    @outstanding.save!
    @retro = Retro.find(params[:retro_id])
    respond_to do |format|
      format.html { redirect_to @retro }
      format.json { render json: @outstanding.id }
      Pusher.trigger('retro_channel', 'complete-task-event', {id: @outstanding.id, complete: @outstanding.complete})
    end
  end

  def destroy
    @outstanding.destroy
    respond_to do |format|
      format.html { redirect_to @retro }
      format.json { render json: params[:id] }
      Pusher.trigger('retro_channel', 'delete-task-event', params[:id])
    end
  end

  private

  def set_outstanding
    @outstanding = Outstanding.find(params[:id])
    @issue = Issue.find(@outstanding.issue_id)
    @retro = Retro.find(@issue.retro_id)
  end

  def outstanding_params
    params.require(:outstanding).permit(:description, :assigned_to, :issue_id)
  end

  def logged_in
    redirect_to login_path if current_user.nil?
  end

  def owner
    @outstanding = Outstanding.find(params[:id])
    redirect_to owner_access_required_path if (
        @outstanding.creator_id != @current_user.id &&
        !@current_user.admin?)
  end

end

app/helpers/outstandings_helper.rb
module OutstandingsHelper
end

app/views/outstandings/_form.html.erb
<h4 align="center"><%= title %></h4>

<form class="form-horizontal" id="new-outstanding-<%= @issue.id %>">
  <fieldset>

    <input name="_method" type="hidden" value="<%=action_method%>" />
    <% if action_method == "PATCH" %>
      <input name="task_id" type="hidden" value="<%= @outstanding.id %>" />
    <% end %>

    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden" />
    <input name="outstanding[issue_id]" value="<%= @issue.id %>" type="hidden" />
    <input name="outstanding[retro_id]" value="<%= @retro.id %>" type="hidden" />

    <!-- Select Multiple -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="assigned_to">assigned to</label>
      <div class="col-md-8">
        <select multiple id="assigned_to" name="assigned_to[]" class="form-control">
          <% User.all.each do |user| %>
              <option
              <% if @outstanding.users.include? (user) %>
              selected="selected"
              <% end %>
              value="<%= user.id %>"><%= user.name %></option>
          <% end %>
          <option
          <% if @outstanding.users.equal? (User.all) %>
          selected="selected"
          <% end %>
          value="-1">all</option>
        </select>
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">'
      <label class="col-md-4 control-label" for="textinput">Description</label>
      <div class="col-md-8">
        <input id="description" name="outstanding[description]" type="text" autofocus="true" placeholder="Description"
               class="form-control input-md" required="" value="<%= @outstanding.description %>">
      </div>
    </div>

    <!-- Button -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="singlebutton"></label>
      <div class="col-md-4">
        <button class="btn btn-primary" onclick="makeTask($('#new-outstanding-<%= @issue.id %>'))">
          <%= button_title %>
        </button>
      </div>
    </div>

  </fieldset>
</form>

app/views/outstandings/_singletask.html.erb
<% if task.complete? %>
    <tr class="strikeout" id = "task-<%= task.id %>">
<% else %>
    <tr id="task-<%= task.id %>">
<% end %>
<td><%=h task.description %></td>
<% if user_page %>
    <td><a href="<%= retro_path(Retro.find(Issue.find(task.issue_id).retro_id)) %>"><%= Retro.find(Issue.find(task.issue_id).retro_id).meeting_date %></a></td>
<% elsif task.users == User.all %>
    <td><a href="<%= users_path %>">all</a></td>
<% else %>
    <td>
      <% task.users.each do |assigned| %>
          <a href="<%= user_path(assigned) %>"><%= assigned.name %></a><br>
      <% end %>
    </td>
<% end %>
<td><a href="<%=issue_path(Issue.find(task.issue_id)) %>"><%= Issue.find(task.issue_id).description %></a></td>
<% if title == "Tasks from Last Week" %>
    <td><a id="completelink-<%=task.id%>" onclick="markAsDone(<%= task.retro_id%>, <%=task.id%>)">
      set as <% if task.complete? %>in<%end%>complete
    </a></td>
<% else %>
    <td><%= link_to 'Edit', edit_outstanding_path(task), remote: true %></td>
<% end %>
<td><a onclick="deleteOutstanding(<%=task.id%>)">Delete</a></td>
</tr>

app/views/outstandings/_tasks.html.erb
<center><h1><%= title %></h1></center>

<table class="table">
  <thead>
  <tr>
    <th>description</th>
    <% if user_page %>
        <th>retro</th>
    <% else %>
        <th>assigned to</th>
    <% end %>
    <th>issue</th>
    <% if title == "Tasks from Last Week" %>
        <th>mark_as_done</th>
    <% end %>
  </tr>
  </thead>

  <tbody id="tasks">
  <% tasks.each do |task| %>
    <%= render partial: "outstandings/singletask", locals: {task:  task,
                                                title: title,
                                                user_page: user_page} %>
      <!--<tr class="row"><td><div id="edit-task-<%=task.id%>" style="display:none; position:absolute;"></div></td></tr>-->
  <% end %>
  </tbody>
</table>
<div id="edit-task" style="display:none; position:absolute;"></div>

app/views/outstandings/create.js.erb
$("#task-form-<%= @issue.id %>").slideUp(350);
$("#task-form-<%= @issue.id %>").html("");
$("#tasks").append("<%= j render(partial:  "outstandings/singletask", locals: {task:  @outstanding,
                                                title: "Tasks for Next Week",
                                                user_page: false}) %>");

app/views/outstandings/edit.html.erb
<%= render partial: "outstandings/form", locals: {
    title: "Edit outstanding",
    button_title: "Modify",
    action: outstanding_path(@outstanding),
    action_method: "PATCH" } %>

<%= link_to 'Show', @outstanding %> |
<%= link_to 'Cancel', retro_issues_path(@retro) %>

app/views/outstandings/edit.js.erb
var editform = $("#edit-task");
if (editform.html() == "") {
    editform.css("width", "75%")
    editform.html("<%= j (render partial: "outstandings/form", locals: {
    title: "Edit task",
    button_title: "Modify",
    action: outstanding_path(@outstanding),
    action_method: "PATCH" }) %>");
    editform.slideDown({duration: 400, progress: function() {window.scrollTo(0,document.body.scrollHeight);}});

}
else {
    editform.slideUp(400, function() {editform.html("");});
}

app/views/outstandings/index.html.erb
<h1>Listing tasks</h1>

<table class="table">
  <thead>
  <tr>
    <th>description</th>
    <th>assigned to</th>
  </tr>
  </thead>

  <tbody>
  <% @tasks.each do |task| %>
      <tr>
        <%= render partial: "outstandings/singletask", locals: {task:  task,
                                                                title: "Listing tasks",
                                                                user_page: false} %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_issue_outstanding_path(@issue.id) %>

app/views/outstandings/new.html.erb
<%= render partial: "outstandings/form", locals: {
    title: "New task",
    button_title: "Add task",
    action: issue_outstandings_path(@retro),
    action_method: "POST" } %>

<%= link_to 'Back to the Retro', retro_issues_path(@retro) %>

app/views/outstandings/new.js.erb
if ($("#task-form-<%= @issue.id %>").html() == "") {
    $("#task-form-<%= @issue.id %>").html("<%= j (render partial: "outstandings/form", locals: {
    title: "New outstanding",
    button_title: "Add outstanding",
    action: issue_outstandings_path(@issue),
    action_method: "POST" }) %>");
    $("#task-form-<%= @issue.id %>").slideDown(400);
}
else {
    $("#task-form-<%= @issue.id %>").slideUp(400);
    $("#task-form-<%= @issue.id %>").html("");
}

app/views/outstandings/show.html.erb
<p>
  <strong>Retrospective:</strong>
  <%= @outstanding.retro_id %>
</p>

<p>
  <strong>Issue:</strong>
  <%= @outstanding.issue_id %>
</p>

<p>
  <strong>Assigned_to:</strong>
  <%= @outstanding.assigned_to %>
</p>

<p>
  <strong>Description:</strong>
  <%= @outstanding.description %>
</p>

<%= link_to 'Edit', edit_outstanding_path(@outstanding) %> |
<%= link_to 'Back to the retro', retro_issues_path(@retro) %>

app/views/outstandings/update.js.erb
$("#edit-task").slideUp(400);
$("#edit-task").html("");
$("#task-<%= @outstanding.id %>").replaceWith("<%= j render(partial:  "outstandings/singletask", locals: {task:  @outstanding,
                                                title: "Tasks for Next Week",
                                                user_page: false}) %>");