config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :projects, shallow: true do
    resources :retros do
      resources :issues do
        resources :outstandings
        resources :votes
      end
    end
  end

  resources :users

  root   'projects#index'

  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'admin_access_required' => 'page#admin_access_required'
  get    'owner_access_required' => 'page#owner_access_required'

  # custom route for moving the retro from one step to the next
  post   'retros/:id/status/:status' => 'retros#transition_status', as: :transition_retro_status
  post 'issues/:issue_id/votes' => 'votes#create', as: :make_new_vote

  get 'users/:retro_id/votes', :to => 'votes#clear_all', as: :clear_user_votes
  post 'retros/:id/discussed', :to => 'retros#increment_discussed_review', as: :increment_discussed_review
  post 'retros/:id/discussed_followup', :to => 'retros#increment_discussed_followup', as: :increment_discussed_followup
  post 'retros/:retro_id/outstandings/:id/complete', :to => 'outstandings#mark_complete', as: :mark_complete

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :retro
  has_many :votes, dependent: :destroy
  has_many :outstandings, dependent: :destroy

  validates :creator_id, presence: true
  validates :retro_id, presence: true
  validates :description, presence: true, length:{ minimum:2 }
  validates :issue_type, presence: true

  def type_to_int
    types = {"Good" => 0, "Meh" => 1, "Bad" => 2}
    types[issue_type]
  end

end

app/controllers/issues_controller.rb
require 'pusher'

Pusher.app_id = '133467'
Pusher.key = 'bec060895b93f6745a24'
Pusher.secret = 'd3e13b0e84b33a44613a'

class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate!, only: [ :index, :show ]
  before_action :owner, only: [ :destroy, :edit ]
  respond_to :js

  def hello_world
    Pusher.trigger('retro_channel', 'my-event', {:message => 'hello world'})
  end

  # GET /issues
  # GET /issues.json
  def index
    @good_issues = Issue.where("retro_id = #{params[:retro_id]} AND issue_type = 'Good'")
    @meh_issues = Issue.where("retro_id = #{params[:retro_id]} AND issue_type = 'Meh'")
    @bad_issues = Issue.where("retro_id = #{params[:retro_id]} AND issue_type = 'Bad'")
    @retro = Retro.find(params[:retro_id])
    @project = Project.find(@retro.project_id)
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
    @issue.issue_type = params[:type]
    @retro = Retro.find(params[:retro_id])
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    @issue.retro_id = params[:retro_id]
    @issue.creator_id = current_user.id
    @retro = Retro.find(params[:retro_id])
    respond_to do |format|
      if @issue.save

        format.html { redirect_to @retro }
        @index = Issue.where("retro_id = #{params[:retro_id]} AND issue_type = '#{@issue.issue_type}'").order('votes_count DESC').index @issue
        format.json { render json: {issue: @issue,
                                    retro: @retro,
                                    index: @index,
                                    creator_name: current_user.name,
                                    issue_type: @issue.type_to_int,
                                    method: "POST" } }
        Pusher.trigger('retro_channel', 'create-issue-event', {issue: @issue,
                                                         retro: @retro,
                                                         index: @index,
                                                         creator_name: current_user.name,
                                                         issue_type: @issue.type_to_int,
                                                         method: "POST" } )
      else
        flash[:error] = @issue.errors
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        @index = Issue.where("retro_id = #{@issue.retro_id} AND issue_type = '#{@issue.issue_type}'").order('votes_count DESC').index @issue
        format.html { redirect_to @retro }
        format.json { render json: {issue: @issue,
                                    retro: @retro,
                                    index: @index,
                                    creator_name: current_user.name,
                                    issue_type: @issue.type_to_int,
                                    method: "PATCH" } }
        Pusher.trigger('retro_channel', 'update-issue-event', {issue: @issue,
                                                               retro: @retro,
                                                               index: @index,
                                                               creator_name: current_user.name,
                                                               issue_type: @issue.type_to_int,
                                                               method: "PATCH" } )
      else
        flash[:error] = @issue.errors
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @index = Issue.where("retro_id = #{@issue.retro_id} AND issue_type = '#{@issue.issue_type}'").order('votes_count DESC').index @issue
    @type = @issue.type_to_int
    @issue.destroy
    respond_to do |format|

      format.html { redirect_to @retro }
      format.json { render json: {index: @index, type: @type } }
      Pusher.trigger('retro_channel', 'delete-issue-event', {index: @index, type: @type })
    end
  end

  private
    # Use callbacks to share common setup or constraints between outstandings.
    def set_issue
      @issue = Issue.find(params[:id])
      @retro = Retro.find(@issue.retro_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:retro_id, :issue_type, :creator_id, :description)
    end

    def owner
      redirect_to owner_access_required_path if ((@issue.creator_id != @current_user.id) && !@current_user.admin?)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def project_name
    Project.find(Retro.find(params[:id][:project_id]))
  end

  def is_owner?
    @current_user.id == @retro.creator_id
  end

  def status_to_int
    Retro.statuses[@retro.status]
  end

  def next_status
    status = status_to_int
    Retro.statuses.find { |k,v| Integer(v) == status + 1 }[0]
  end

  def status_title
    ['Start Retro',
     'Add Issues',
     'Review Issues',
     'Begin Voting',
     'Close Voting',
     'Finish Retro',
     'Restart'][status_to_int]
  end
end

app/views/issues/_form.html.erb
<h1 align="center"><%= title %></h1>
<form class="form-horizontal" id="new_issue_<%= @issue.issue_type %>">
  <fieldset>

    <input name="_method" type="hidden" value="<%=action_method%>"/>
    <% if action_method == "PATCH" %>
        <input name="issue_id" type="hidden" value="<%=@issue.id%>" />
    <% end %>

    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden" />
    <input name="issue[retro_id]" value="<%= @retro.id %>" type="hidden" />

    <!-- Select Multiple -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="issue_type">Type</label>
      <div class="col-md-8">
        <select id="issue_type" name="issue[issue_type]" class="form-control">
          <% for type in ["Good","Meh","Bad"] %>
              <option
              <% if @issue.issue_type == type %>
              selected="selected"
              <% end %>
              value="<%= type %>"><%= type %></option>
          <% end %>
        </select>
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="textinput">Description</label>
      <div class="col-md-8">
        <input id="description" name="issue[description]" type="text" autofocus="true" placeholder="Description" class="form-control input-md" required="" value="<%= @issue.description %>">
      </div>
    </div>

    <!-- Button -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="singlebutton"></label>
      <div class="col-md-4">
        <button class="btn btn-primary" onclick="makeIssue($('#new_issue_<%= @issue.issue_type %>'))">
          <%= button_title %>
        </button>
      </div>
    </div>

  </fieldset>
</form>

app/views/issues/_issuetemplate.html.erb
<li id="issue-<%=index%>-<%=type%>" class="data <% if issue %><%= issue_class %><% end %>">
  <% if !issue.nil? %>

      <% if issue.creator_id.nil? %>
          Unknown
      <% else %>
          <%= link_to user(issue.creator_id).name, user_path(issue.creator_id) %>
      <% end %>
      <% if (@retro.status == "in_review" || @retro.status == "voted_review") &&
              (@retro.discussed_index == index) && (@retro.discussed_type == type)%>
          <b id='discussed'><span id="description"><%= issue.description %></span></b>
      <% else %>
          <span id="description"><%=h issue.description %></span>
      <% end %>


      <a onclick="deleteIssue(<%= issue.id %>)" style="float: right;" >
        <span class="glyphicon glyphicon-trash"></span>
      </a>
      <a href="<%= edit_issue_path(issue) %>" style="float: right;" data-remote="true"><span class="glyphicon glyphicon-pencil"></span></a>
      <% if @retro.status == "voted_review" || @retro.status =="complete" %>
          <div align="right">votes: <%= issue.votes_count %></div>
      <% end %>
      <% if @retro.status == "voted_review" %>
          <%= link_to 'New Task', new_issue_outstanding_path(issue_id: issue.id), remote: true %>
          <div id="task-form-<%=issue.id %>" style="display:none;"></div>
      <% end %>
      <% if @retro.status == "voting" %>
          <form>
            <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden" />
            <button id="submit" name="submit" class="btn btn-default" onclick="addVote(<%=issue.id%>)">
              <span id="votecount-<%=issue.id%>"><%= issue.votes_count %></span>
            </button>
          </form>
      <% end %>
      <div id="edit-<%=issue.id %>" style="display:none;"></div>

  <% else %>
      &nbsp;
  <% end %>
</li>

app/views/issues/create.js.erb
$("#add-issue-<%= @issue.issue_type %>").slideUp(400);
$("#add-issue-<%= @issue.issue_type %>").html("");
$("#<%=@issue.issue_type %>_issues").append("<%= j render(partial: "issues/issuetemplate", locals: {
 issue: @issue,
 issue_class: "retro-#{@issue.issue_type}",
 index: @index,
 type: @issue.type_to_int }) %>");
$("#<%=@issue.issue_type %>_issues").append($("#<%= @issue.issue_type %>_adder"));

app/views/issues/edit.html.erb
<%= render partial: "issues/form", locals: {
    title: "Edit issue",
    button_title: "Modify",
    action: issue_path(@issue),
    action_method: "PATCH" } %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Cancel', retro_issues_path(@retro) %>

app/views/issues/edit.js.erb
if ($("#edit-<%= @issue.id %>").html() == "") {
    $("#edit-<%= @issue.id %>").html("<%= j render( partial: "issues/form", locals: {
    title: "Edit issue",
    button_title: "Modify",
    action: issue_path(@issue),
    action_method: "PATCH" } )%>");
    $("#edit-<%= @issue.id %>").slideDown(400);
}
else {
    $("#edit-<%= @issue.id %>").slideUp(400);
    $("#edit-<%= @issue.id %>").html("");
}

app/views/issues/index.html.erb
<h4>
<form method="post" action="<%= transition_retro_status_path(:id=>@retro.id, :status => next_status) %>">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden" />
  <button id="submit" name="submit" class="btn btn-primary">
    <%= status_title %>
  </button>
  <%= @project.name %> - <%= @retro.meeting_date %></h4>
</form>
<% if @retro.status == "voting" %>
    <p>Number of votes: <span id="votecount-primary"><%= current_user.votes.where(retro_id: @retro.id).count %></span></p>
    <form>
      <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden" />
      <button id="clear_votes" onclick="clearVotes(<%=@retro.id%>)" class="btn btn-default">
        clear votes
      </button>
    </form>
<% end %>

<% if @retro.status == "voted_review" || @retro.status == "complete" %>
    <% @good_issues = @good_issues.order('votes_count DESC') %>
    <% @meh_issues = @meh_issues.order('votes_count DESC') %>
    <% @bad_issues = @bad_issues.order('votes_count DESC') %>
<% end %>

<div class="column">
  <ul class="list" id="Good_issues">
    <li class="title retro-header retro-Good">
      <% if @retro.status == "adding_issues" || @retro.status == "in_review" %>
          <a data-remote="true" href="<%= new_retro_issue_path(@retro) %>?type=Good">
            <span  class="glyphicon glyphicon-plus"></span>
          </a>
      <% end %>
      The good<%= image_tag("#{@retro.good_icon}.png", :size=>"100x100", :align=>"right") %>
    </li>
    <% for index in 0..@good_issues.size-1 %>
      <%= render partial: "issues/issuetemplate", locals: { issue: @good_issues[index],
                                                            issue_class: 'retro-Good',
                                                            index: index,
                                                            type: 0 } %>
    <% end %>
    <% if @retro.status == "adding_issues" || @retro.status == "in_review" %>
        <li class="data retro-Good" id="Good_adder">
          <div id="add-issue-Good" style="display:none;"></div>
        </li>
    <% end %>
  </ul>
</div>

<div class="column">
  <ul class="list" id="Meh_issues">
    <li class="title retro-header retro-Meh">
        <% if @retro.status == "adding_issues" || @retro.status == "in_review" %>
          <a data-remote="true" href="<%= new_retro_issue_path(@retro) %>?type=Meh">
            <span class="glyphicon glyphicon-plus"></span>
          </a>
      <% end %>
      The meh
      <%= image_tag("#{@retro.meh_icon}.png", :size=>"100x100", :align=>"right") %>
    </li>
    <% for index in 0..@meh_issues.size-1 %>
        <%= render partial: "issues/issuetemplate", locals: { issue: @meh_issues[index],
                                                              issue_class: 'retro-Meh',
                                                              index: index,
                                                              type: 1 } %>
    <% end %>
    <% if @retro.status == "adding_issues" || @retro.status == "in_review" %>
        <li class="data retro-Meh" id="Meh_adder">
          <div id="add-issue-Meh" style="display:none;"></div>
        </li>
    <% end %>
  </ul>
</div>

<div class="column">
  <ul class="list" id="Bad_issues">
    <li class="title retro-header retro-Bad">
      <% if @retro.status == "adding_issues" || @retro.status == "in_review" %>
          <a data-remote="true" href="<%= new_retro_issue_path(@retro) %>?type=Bad">
            <span class="glyphicon glyphicon-plus"></span>
          </a>
      <% end %>
      The ugly
      <%= image_tag("#{@retro.bad_icon}.png", :size=>"100x100", :align=>"right") %>
    </li>
    <% for index in 0..@bad_issues.size-1 %>
        <%= render partial: "issues/issuetemplate", locals: { issue: @bad_issues[index],
                                                              issue_class: 'retro-Bad',
                                                              index: index,
                                                              type: 2 } %>
    <% end %>
    <% if @retro.status == "adding_issues" || @retro.status == "in_review" %>
        <li class="data retro-Bad" id="Bad_adder">
          <div id="add-issue-Bad" style="display:none;"></div>
        </li>
    <% end %>
  </ul>
</div>


<div class="realign-below-list">

<% if @retro.status == "in_review" %>
    <form id="timer">
      <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden" />
      <button id="next_issue" name="next_issue" class="btn btn-default" onclick="nextReview(<%=@retro.id%>, document.querySelector('#time'))">
        <span><span id="time">00:30 seconds remaining, </span>click to proceed to next topic</span>
      </button>
    </form>
<% end %>
<% if @retro.status == "voted_review" %>
    <form>
      <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden" />
      <button id="next_issue" name="next_issue" class="btn btn-default" onclick="nextVotedReview(<%=@retro.id%>)">
        <div>click to proceed to next topic</div>
      </button>
    </form>
<% end %>

<br>
<% if @retro.status == "review_last_retro" %>
    <% @all_retros = Retro.where("project_id = #{@retro.project_id}").order('meeting_date ASC') %>
    <% @current_index = @all_retros.index @retro %>
    <% @current_index -= 1 %>
    <% if !@all_retros[@current_index].nil? %>
        <%= render partial: "outstandings/tasks", locals: {
                                                        tasks: Outstanding.where("retro_id = #{@all_retros[@current_index].id}"),
                                                        title: "Tasks from Last Week",
                                                        user_page: false }%>
    <% end %>
<% end %>

<% if @retro.status == "voted_review" || @retro.status == "complete" %>
    <% @all_retros = Retro.where("project_id = #{@retro.project_id}").order('meeting_date DESC') %>
    <% @current_index = @all_retros.index @retro %>
    <% @current_index -= 1 %>
    <% if !@all_retros[@current_index].nil? %>
        <%= render partial: "outstandings/tasks", locals: {
                                                    tasks: Outstanding.where("retro_id = #{@retro.id} OR
                                                                              (retro_id = #{@all_retros[@current_index].id} AND
                                                                              complete = 'f' )"),
                                                    title: "Tasks for Next Week",
                                                    user_page: false }%>
    <% else %>
        <%= render partial: "outstandings/tasks", locals: {
                                                        tasks: Outstanding.where("retro_id = #{@retro.id}"),
                                                        title: "Tasks for Next Week",
                                                        user_page: false }%>
    <% end %>
<% end %>

<% if @retro.status == "adding_issues" || @retro.status == "in_review" %>
    <a href="/retros/<%=@retro.id%>/issues/new" data-remote="true" id="general-new-issue">New Issue</a> |
<% end %>
<%= link_to 'All Retros', project_retros_path(@project) %>
  <div id="add-issue-general" style="display:none; position:absolute;"></div>
</div>


<script type="text/javascript">
  function setHeight() {
      var belowList = $(".realign-below-list");
      var height = belowList.css("height");
      belowList.css("bottom", "-"+height);
  }
  window.onload = setHeight();
</script>
<% if @retro.status == "in_review" %>
    <script type="text/javascript">
      window.onload = startTimer(30, document.querySelector('#time'));
    </script>
<% end %>

app/views/issues/new.html.erb
<%= render partial: "issues/form", locals: {
    title: "New issue",
    button_title: "Add item",
    action: retro_issues_path(@retro),
    action_method: "POST" } %>

<%= link_to 'Back to the Retro', retro_issues_path(@retro) %>

app/views/issues/new.js.erb
if (<%= @issue.issue_type.nil? %>) {
    var general = $("#add-issue-general");
    if (general.html() == "") {
        general.css("width", "75%")
        general.html("<%= j (render partial: "issues/form", locals: {
        title: "New issue",
        button_title: "Add item",
        action: retro_issues_path(@retro),
        action_method: "POST" }) %>");
        general.slideDown(400);
    }
    else {
        general.slideUp(400, function() {general.html("");});
    }
}
else if ($("#add-issue-<%= @issue.issue_type %>").html() == "") {
    $("#add-issue-<%= @issue.issue_type %>").html("<%= j (render partial: "issues/form", locals: {
    title: "New issue",
    button_title: "Add item",
    action: retro_issues_path(@retro),
    action_method: "POST" }) %>");
    $("#add-issue-<%= @issue.issue_type %>").slideDown(400);
}
else {
    $("#add-issue-<%= @issue.issue_type %>").slideUp(400, function() {$("#add-issue-<%= @issue.issue_type %>").html("");});

}

app/views/issues/show.html.erb
<p>
  <strong>Retrospective:</strong>
  <%= @issue.retro_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @issue.issue_type %>
</p>

<p>
  <strong>Owner:</strong>
  <%= user(@issue.creator_id).name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @issue.description %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back to the retro', retro_issues_path(@retro) %>

app/views/issues/update.js.erb
$("#edit-<%= @issue.id %>").slideUp(400, function() {
    $("#issue-<%= @index %>-<%= @issue.type_to_int %>").replaceWith("<%= j render(partial: "issues/issuetemplate", locals: {
 issue: @issue,
 issue_class: "retro-#{@issue.issue_type}",
 index: @index,
 type: @issue.type_to_int }) %>");
});