config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :projects, shallow: true do
    resources :retros do
      resources :issues do
        resources :outstandings
        resources :votes
      end
    end
  end

  resources :users

  root   'projects#index'

  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'admin_access_required' => 'page#admin_access_required'
  get    'owner_access_required' => 'page#owner_access_required'

  # custom route for moving the retro from one step to the next
  post   'retros/:id/status/:status' => 'retros#transition_status', as: :transition_retro_status
  post 'issues/:issue_id/votes' => 'votes#create', as: :make_new_vote

  get 'users/:retro_id/votes', :to => 'votes#clear_all', as: :clear_user_votes
  post 'retros/:id/discussed', :to => 'retros#increment_discussed_review', as: :increment_discussed_review
  post 'retros/:id/discussed_followup', :to => 'retros#increment_discussed_followup', as: :increment_discussed_followup
  post 'retros/:retro_id/outstandings/:id/complete', :to => 'outstandings#mark_complete', as: :mark_complete

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :retros, dependent: :destroy

  validates :owner_id, presence: true
  #validates :description, presence: true
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:edit, :update, :new]
  skip_before_action :authenticate!, only: [ :index, :show ]
  before_action :is_admin, only: [:edit, :update, :destroy, :create, :new]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.owner_id = current_user.id
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        flash[:success] = "Project #{@project.name} was successfully created."
        format.html { redirect_to project_retros_path(@project) }
        format.json { render :show, status: :created, location: @project }
      else
        flash[:error] = @project.errors
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        flash[:success] = "Project #{@project.name} was successfully updated."
        format.html { redirect_to root_path }
        format.json { render :show, status: :ok, location: @project }
      else
        flash[:error] = @project.errors
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      flash[:success] = "Project #{@project.name} was successfully destroyed."
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between outstandings.
    def set_project
      @project = Project.find(params[:id])
    end

    def set_users
      @users = User.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :owner_id)
    end

  def is_admin
    redirect_to owner_access_required_path if !@current_user.admin?
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<form class="form-horizontal" action="<%= action %>" method="POST">
  <fieldset>

    <!-- Form Name -->
    <legend><%= title %></legend>
    <% if action_method == "PATCH" %>
        <input name="_method" type="hidden" value="patch" />
    <% end %>

    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden" />

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="project_name">Project Name</label>
      <div class="col-md-4">
        <input id="project_name" name="project[name]" type="text" placeholder="Your team name here" class="form-control input-md" required="" value="<%= @project.name %>">

      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="description">Description</label>
      <div class="col-md-4">
        <input id="description" name="project[description]" type="text" placeholder="Optional" class="form-control input-md" value="<%= @project.description %>">

      </div>
    </div>

    <!-- Select input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="project[owner]">Owner</label>
      <div class="col-md-4">
        <select id="owner" name="project[owner_id]" class="form-control">
          <% for user in @users %>
              <option value="<%= user.id %>"
              <% if @project.owner_id == user.id %>
                  selected="<%= user.id %>"
              <% end %>
                  ><%= user.name %> (<%= user.email %>)></option>
          <% end %>
        </select>
      </div>
    </div>

    <!-- Button -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="submit"></label>
      <div class="col-md-4">
        <button id="submit" name="submit" class="btn btn-primary"><%= button_title %></button>
      </div>
    </div>

  </fieldset>
</form>

app/views/projects/edit.html.erb
<%= render partial: "projects/form", locals: {
        title: "Edit project",
        button_title: "Change project",
        action: project_path(@project),
        action_method: "PATCH" } %>

<%= link_to 'Back to Projects page', projects_path %>

app/views/projects/index.html.erb
<div class="container">
  <div class="row">
  <% for i in 0..@projects.size-1 %>
     <% project = @projects[i] %>
      <div data-retros-url="<%= project_retros_path(project) %>" class="col-xd-4 col-xs-4 col-md-4 project-card">
          <a href="<%= project_path(project) %>" style="float: right;" data-method="DELETE" data-confirm="Are you sure?" rel="nofollow">
            <span class="glyphicon glyphicon-trash"></span>
          </a>
          <a href="<%= edit_project_path(project) %>" style="float: right;"><span class="glyphicon glyphicon-pencil"></span></a>
          [<%= project.id %>] <%= project.name %><br>
          <%= project.description %><br>
          Owned by <a href="<%= user_path(user(project.owner_id)) %>"><%= user(project.owner_id).name %></a><br>
      </div>
  <% end %>
  </div>
</div>

<div class="row">
    <%= link_to 'New Project', new_project_path %>
</div>

app/views/projects/new.html.erb
<%= render partial: "projects/form", locals: {
        title: "New project",
        button_title: "Create project",
        action: projects_path,
        action_method: "POST" } %>

<%= link_to 'Cancel', projects_path %>

app/views/projects/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @project.owner_id %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Cancel', projects_path %>