config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :projects, shallow: true do
    resources :retros do
      resources :issues do
        resources :outstandings
        resources :votes
      end
    end
  end

  resources :users

  root   'projects#index'

  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'admin_access_required' => 'page#admin_access_required'
  get    'owner_access_required' => 'page#owner_access_required'

  # custom route for moving the retro from one step to the next
  post   'retros/:id/status/:status' => 'retros#transition_status', as: :transition_retro_status
  post 'issues/:issue_id/votes' => 'votes#create', as: :make_new_vote

  get 'users/:retro_id/votes', :to => 'votes#clear_all', as: :clear_user_votes
  post 'retros/:id/discussed', :to => 'retros#increment_discussed_review', as: :increment_discussed_review
  post 'retros/:id/discussed_followup', :to => 'retros#increment_discussed_followup', as: :increment_discussed_followup
  post 'retros/:retro_id/outstandings/:id/complete', :to => 'outstandings#mark_complete', as: :mark_complete

end

app/models/retro.rb
class Retro < ActiveRecord::Base
  belongs_to :project
  has_many :issues, dependent: :destroy

  enum status: %w(not_started review_last_retro adding_issues in_review voting voted_review complete restart)

  validates :creator_id, presence: true
  validates :meeting_date, presence: true, uniqueness: true
  validates :project_id, presence: true
  validates_inclusion_of :status, in: Retro.statuses.keys

  def int_to_type
    types =['Good', 'Meh', 'Bad']
    types[discussed_type]
  end

  def to_json
    {}
  end


end

app/controllers/retros_controller.rb
require 'pusher'

Pusher.app_id = '133467'
Pusher.key = 'bec060895b93f6745a24'
Pusher.secret = 'd3e13b0e84b33a44613a'


class RetrosController < ApplicationController
  before_action :logged_in
  before_action :set_retro, only: [ :show, :edit, :update, :destroy, :transition_status, :increment_discussed_review, :increment_discussed_followup ]
  before_action :set_project, only: [ :index ]
  skip_before_action :authenticate!, only: [ :index, :show ]
  before_action :admin_access?, only: [ :destroy ]
  before_action :owner_access, only: [ :edit, :update, :destroy, :transition_status, :increment_discussed_review, :increment_discussed_followup]

  # GET /retros
  # GET /retros.json
  def index
    @retros = Retro.where("project_id = #{params[:project_id]}").order("meeting_date DESC")
  end

  # GET /retros/1
  # GET /retros/1.json
  def show
    redirect_to retro_issues_path(@retro)
  end

  # GET /retros/new
  def new
    @retro = Retro.new
    @retro.project_id = params[:project_id]
    @time = Time.current
    if @time.month == 4 && @time.day == 1
      @retro.good_icon = 100
      @retro.meh_icon = 100
      @retro.bad_icon = 100
    else
      @retro.good_icon = rand(52)
      loop do
        @retro.meh_icon = rand(52)
        break if @retro.meh_icon != @retro.good_icon
      end
      loop do
        @retro.bad_icon = rand(52)
        break if @retro.bad_icon != @retro.good_icon && @retro.bad_icon != @retro.meh_icon
      end
    end
  end

  # GET /retros/1/edit
  def edit
  end

  # POST /retros
  # POST /retros.json
  def create
    puts retro_params
    @retro = Retro.new(retro_params)
    @retro.creator_id = current_user.id
    @retro.project_id = params[:project_id]
    @retro.meeting_date = Date.today
    @retro.status = "not_started"
    @time = Time.new
    if @time.month == 4 && @time.day == 1
      @retro.good_icon = 100
      @retro.meh_icon = 100
      @retro.bad_icon = 100
    else
      @retro.good_icon = rand(52)
      loop do
        @retro.meh_icon = rand(52)
        break if @retro.meh_icon != @retro.good_icon
      end
      loop do
        @retro.bad_icon = rand(52)
        break if @retro.bad_icon != @retro.good_icon && @retro.bad_icon != @retro.meh_icon
      end
    end
    respond_to do |format|
      if @retro.save
        format.html { redirect_to @retro }
        format.json { render :show, status: :created, location: @retro }
        Pusher.trigger('retro_channel', 'new-retro-event', {retro: @retro, user: current_user, date: @retro.meeting_date.strftime("%F") })
      else
        format.html { render :new }
        format.json { render json: @retro.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /retros/1/status/adding_issues
  def transition_status
    # TODO: make sure the transition is valid
    status = params[:status]
    if (Retro.statuses[status] == Retro.statuses[:restart])
      @retro.not_started!
    else
      @retro.status = status
    end
    if (@retro.status == "voted_review" && Issue.where("retro_id = #{@retro.id}").exists?)
      @issues = Issue.where("retro_id = #{@retro.id}").order('votes_count DESC')
      @retro.discussed_type = Issue.where("retro_id = #{@retro.id}").order('votes_count DESC')[0].type_to_int
    else
      @issues = Issue.where("retro_id = #{@retro.id}").sort_by{|issue| issue.type_to_int}
      if !@issues.empty?
        @retro.discussed_type = @issues[0].type_to_int
      end
    end
    @retro.discussed_index = 0
    if @retro.status == "voted_review"
      @last_retro_index = (Retro.where("project_id = #{@retro.project_id}").order('meeting_date DESC').index @retro)-1
      @last_retro = Retro.where("project_id = #{@retro.project_id}").order('meeting_date DESC')[@last_retro_index]
      if !@last_retro.nil?
        @further_tasks = Outstanding.where("retro_id = #{@last_retro.id} AND !complete")
      end
    end
    @retro.save!
    redirect_to retro_issues_path(@retro)
    Pusher.trigger('retro_channel', 'transition-retro-status-event', @retro.id)
  end

  # PATCH/PUT /retros/1
  # PATCH/PUT /retros/1.json
  def update
    respond_to do |format|
      if @retro.update(retro_params)
        format.html { redirect_to @retro }
        format.json { render :show, status: :ok, location: @retro }
      else
        flash[:error] = @retro.errors
        format.html { render :edit }
        format.json { render json: @retro.errors, status: :unprocessable_entity }
      end
    end
  end

  def increment_discussed_review
    @num_passed = 0
    loop do
      break unless Issue.where("retro_id = #{@retro.id}").exists?
      if @retro.discussed_type.nil? || @num_passed >= 3
        @retro.discussed_type = Issue.where("retro_id = #{@retro.id}").sort_by{|issue| issue.type_to_int}[0].type_to_int
        @retro.discussed_index = 0
      elsif @retro.discussed_type == 2
        @retro.discussed_type = 0
        @retro.discussed_index += 1
        @num_passed = 0
      else
        @retro.discussed_type += 1
      end
      break unless Issue.where("retro_id = #{@retro.id} AND issue_type = '#{@retro.int_to_type}'").size <= @retro.discussed_index
      @num_passed += 1
    end
    @retro.save!
    respond_to do |format|
      format.html { redirect_to retro_issues_path(@retro) }
      format.json { render json: {index: @retro.discussed_index, type: @retro.int_to_type}, status: :ok}
      Pusher.trigger('retro_channel', 'next-review-event', {index: @retro.discussed_index, type: @retro.int_to_type})
    end

  end

  def increment_discussed_followup
    @issues = Issue.where("retro_id = #{params[:id]}").order('votes_count DESC')
    @good_issues = Issue.where("retro_id = #{params[:id]} AND issue_type = 'Good'").order('votes_count DESC')
    @meh_issues = Issue.where("retro_id = #{params[:id]} AND issue_type = 'Meh'").order('votes_count DESC')
    @bad_issues = Issue.where("retro_id = #{params[:id]} AND issue_type = 'Bad'").order('votes_count DESC')
    if @issues.exists?
      @issue_types = { "Good" => @good_issues, "Meh" => @meh_issues, "Bad" => @bad_issues }
      @location = @issues.index @issue_types[@retro.int_to_type][@retro.discussed_index]
      if @location.nil?
        @location = @issue_types[@retro.int_to_type].size-1
      end
      @location+=1
      if @issues[@location].nil?
        @retro.discussed_type = @issues[0].type_to_int
        @retro.discussed_index = 0
      else
        @retro.discussed_type = @issues[@location].type_to_int
        @discussed_type_array = @issue_types[@issues[@location].issue_type]
        @retro.discussed_index = @discussed_type_array.index @issues[@location]
      end
    end
    @retro.save!
    respond_to do |format|
      format.html { redirect_to retro_issues_path(@retro) }
      format.json { render json: {index: @retro.discussed_index, type: @retro.int_to_type}, status: :ok}
      Pusher.trigger('retro_channel', 'next-voted-review-event', {index: @retro.discussed_index, type: @retro.int_to_type})
    end
  end

  # DELETE /retros/1
  # DELETE /retros/1.json
  def destroy
    @retro.destroy
    respond_to do |format|
      format.html { redirect_to project_retros_path(@retro.project_id) }
      format.json { render json: @retro.id }
      Pusher.trigger('retro_channel', 'delete-retro-event', @retro.id)
    end
  end

  private
    # Use callbacks to share common setup or constraints between outstandings.
    def set_retro
      @retro = Retro.find(params[:id])
      set_project
    end

    def set_project
      @project ||= Project.find(params[:project_id] || @retro.project_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def retro_params
      params.require(:retro).permit(:meeting_date, :project_id, :status)
    end

    def logged_in
     redirect_to login_path if current_user.nil?
    end

  def owner_access
    redirect_to :back if ((@retro.creator_id != @current_user.id) && !@current_user.admin?)
  end
end

app/helpers/retros_helper.rb
module RetrosHelper
end

app/views/retros/_form.html.erb
<%= form_for(@retro) do |f| %>
  <% if @retro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@retro.errors.count, "error") %> prohibited this retro from being saved:</h2>

      <ul>
      <% @retro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meeting_date %><br>
    <%= f.datetime_select :meeting_date %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/retros/_new.html.erb
<% if @project == nil %>
    <% @project = Project.find(params[:project_id]) %>
<% end %>
<form class="form-horizontal" id="new_retro">
  <fieldset>

    <!-- Form Name -->
    <legend>New retrospective for <%= @project.name %></legend>

    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden" />
    <input name="project_id" type="hidden" value="<%=params[:project_id]%>"/>
    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="today">Today's date</label>
      <div class="col-md-4">
        <input id="today" name="retro[meeting_date]" type="text" value="<%= Date.today.to_date %>" class="form-control input-md" required="" readonly>
      </div>
    </div>

    <!-- Button -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="submit"></label>
      <div class="col-md-4">
        <button onclick="makeRetro($('#new_retro'))" class="btn btn-primary">Create retrospective</button>
      </div>
    </div>

  </fieldset>
</form>

<%= link_to 'Cancel', new_project_retro_path(@project), remote: true %>

app/views/retros/edit.html.erb
<h1>Editing retro</h1>

<%= render 'form' %>

<%= link_to 'Show', @retro %> |
<%= link_to 'Cancel', retro_path(@retro.id) %>

app/views/retros/index.html.erb
<h1>
  <a href="<%= project_path(@project) %>"> <%= @project.name %></a> - Retros
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Retro ID</th>
      <th>Meeting date</th>
      <th>Created by</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="retro-list">
    <% @retros.each do |retro| %>
      <tr id="retro-<%=retro.id%>">
        <td><%= retro.id %></td>
        <td><a href="<%= retro_path(retro) %>"><%= retro.meeting_date.strftime "%F" %></a></td>
        <td>
          <% if retro.creator_id.nil? %>
            Unknown
          <% else %>
            <a href="<%= user_path(user(retro.creator_id)) %>"><%= user(retro.creator_id).name %> (<%= user(retro.creator_id).email %>)</a>
          <% end %>
        </td>
        <td><%= retro.status %></td>
        <td><a onclick="deleteRetro(<%=retro.id%>)">Destroy</a></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="retro-form" style="display: none;"></div>
<%= link_to 'New Retro', new_project_retro_path(@project), remote: true %> |
<%= link_to 'Projects list', projects_path %>

app/views/retros/new.html.erb
<% if @project == nil %>
    <% @project = Project.find(params[:project_id]) %>
<% end %>
<form class="form-horizontal" action="<%= project_retros_path(@project.id) %>" method="POST">
  <fieldset>

    <!-- Form Name -->
    <legend>New retrospective for <%= @project.name %></legend>

    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden" />

    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="today">Today's date</label>
      <div class="col-md-4">
        <input id="today" name="retro[meeting_date]" type="text" value="<%= Date.today.to_date %>" class="form-control input-md" required="" readonly>
      </div>
    </div>

    <!-- Button -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="submit"></label>
      <div class="col-md-4">
        <button id="submit" name="submit" class="btn btn-primary">Create retrospective</button>
      </div>
    </div>

  </fieldset>
</form>

<%= link_to 'Cancel', project_retros_path(@project) %>

app/views/retros/new.js.erb
if ($("#retro-form").html() == "") {
    $("#retro-form").html("<%= j (render partial: "retros/new") %>").slideDown(400);
}
else {
    $("#retro-form").html("");
    $("#retro-form").slideUp(400);
}

app/views/retros/show.html.erb
<p>
  <strong>Meeting date:</strong>
  <%= @retro.meeting_date %>
</p>

<p>
  <strong>Project:</strong>
  <%= @retro.project_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @retro.status %>
</p>

<%= link_to 'Edit', edit_retro_path(@retro) %> |
<%= link_to 'Retros list', project_retros_path(@retro) %>